pcshop/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('shop.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('produse/<str:categorie>/', views.pagina_categorie, name='categorie'),
    path('<str:categorie>/<int:id>/', views.produs, name='produs'),
    path('<str:categorie>/<int:id>/review/', views.review, name='review'),
    path('<str:categorie>/<int:id>/compara/', views.compara, name='compara'),
    path('cos/', views.cos, name='cos'),
    path('cos/<str:metoda>/<str:categorie>/<int:id>/', views.modifica_cos, name='modifica_cos'),
    path('comenzi/', views.comenzile_mele, name='comenzi'),
    path('checkout/', views.checkout, name='checkout'),
    path('register/', views.pagina_inregistrare, name='register'),
    path('login/', views.pagina_logare, name="login"), 
    path('logout/', views.pagina_delogare, name="logout"),
    path('user/', views.pagina_user, name="user") 
]

shop/models.py
from django.db import models
from django.conf import settings

from django.contrib.auth.models import User


class ExtendUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    # Folosit la comanda pentru cei care nu au cont
    nume = models.CharField(max_length=200)
    adresa_livrare = models.CharField(max_length=200)
    judet = models.CharField(max_length=200)
    oras = models.CharField(max_length=200)
    cod_postal = models.CharField(max_length=200)
    telefon = models.CharField(max_length=200)

    def __str__(self):
        return self.nume

class ComandaProdus(models.Model):
    nume = models.CharField(max_length=200)
    cantitate = models.IntegerField()
    pret_unitar = models.IntegerField()
    pret_total = models.IntegerField()
    poza = models.ImageField()

    def __str__(self):
        return f"{self.nume} | {self.cantitate} | {self.pret_unitar} | {self.pret_total}"

class Comanda(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE,
                             null=True)
    extend_user = models.ForeignKey(ExtendUser,
                                    on_delete=models.CASCADE,
                                    null=True)
    client = models.BooleanField()
    pret_total = models.IntegerField()
    produse = models.ManyToManyField(ComandaProdus, blank=True)

    statusuri = (
        ('Initiata', 'Initiata'),
        ('Procesare', 'Procesare'),
        ('Livrare', 'Livrare'),
        ('Livrata', 'Livrata'),
        ('Anulata', 'Anulata'),
    )
    status = models.CharField(max_length=10, choices=statusuri, default='Initiata')

    def proceseaza_produse(self):
        return ",".join([p.nume for p in self.produse.all()])

    class Meta:
        verbose_name_plural = "Comenzi"

class Review(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    score = models.IntegerField()
    comment = models.CharField(max_length=200)


class Procesor(models.Model):
    nume = models.CharField(max_length=200)
    pret = models.IntegerField()
    cantitate = models.IntegerField()
    separat = models.BooleanField()
    socket = models.CharField(max_length=200)
    nucleu = models.CharField(max_length=200)
    nr_nuclee = models.IntegerField()
    nr_threaduri = models.IntegerField()
    frecventa = models.CharField(max_length=200)
    poza = models.ImageField(upload_to='procesor', default='dummy_image.jpg')
    reviews = models.ManyToManyField(Review, blank=True)

    class Meta:
        verbose_name_plural = "Procesoare"

    def __str__(self):
        return f"{self.nume}"


class PlacaDeBaza(models.Model):
    nume = models.CharField(max_length=200)
    pret = models.IntegerField()
    cantitate = models.IntegerField()
    separat = models.BooleanField()
    format_placa_de_baza = models.CharField(max_length=200)
    soclu_procesor = models.CharField(max_length=200)
    producator_chipset = models.CharField(max_length=200)
    tip_memorie_suportata = models.CharField(max_length=200)
    memorie_maxima_suportata = models.CharField(max_length=200)
    memorie_sloturi = models.CharField(max_length=200)
    poza = models.ImageField(upload_to='placa_de_baza',
                             default='dummy_image.jpg')
    reviews = models.ManyToManyField(Review, blank=True)

    class Meta:
        verbose_name_plural = "Placi de baza"

    def __str__(self):
        return f"{self.nume}"


class PlacaVideo(models.Model):
    nume = models.CharField(max_length=200)
    pret = models.IntegerField()
    cantitate = models.IntegerField()
    separat = models.BooleanField()
    interfata = models.CharField(max_length=200)
    rezolutie_maxima = models.CharField(max_length=200)
    producator_chipset = models.CharField(max_length=200)
    tip_memorie = models.CharField(max_length=200)
    dimensiune_memorie = models.CharField(max_length=200)
    bus_memorie = models.CharField(max_length=200)
    poza = models.ImageField(upload_to='placa_video',
                             default='dummy_image.jpg')
    reviews = models.ManyToManyField(Review, blank=True)

    class Meta:
        verbose_name_plural = "Placi video"

    def __str__(self):
        return f"{self.nume}"


class Memorie(models.Model):
    nume = models.CharField(max_length=200)
    pret = models.IntegerField()
    cantitate = models.IntegerField()
    separat = models.BooleanField()
    tip_memorie = models.CharField(max_length=200)
    capacitate = models.CharField(max_length=200)
    frecventa = models.CharField(max_length=200)
    poza = models.ImageField(upload_to='memorie', default='dummy_image.jpg')
    reviews = models.ManyToManyField(Review, blank=True)

    class Meta:
        verbose_name_plural = "Memorii"

    def __str__(self):
        return f"{self.nume}"


class Stocare(models.Model):
    nume = models.CharField(max_length=200)
    pret = models.IntegerField()
    cantitate = models.IntegerField()
    separat = models.BooleanField()
    tip = models.CharField(max_length=200)
    capacitate = models.CharField(max_length=200)
    viteza_scriere = models.CharField(max_length=200)
    viteza_citire = models.CharField(max_length=200)
    poza = models.ImageField(upload_to='stocare', default='dummy_image.jpg')
    reviews = models.ManyToManyField(Review, blank=True)

    class Meta:
        verbose_name_plural = "Stocare"

    def __str__(self):
        return f"{self.nume}"


class Sursa(models.Model):
    nume = models.CharField(max_length=200)
    pret = models.IntegerField()
    cantitate = models.IntegerField()
    separat = models.BooleanField()
    tip = models.CharField(max_length=200)
    putere = models.CharField(max_length=200)
    numar_ventilatoare = models.CharField(max_length=200)
    voltaj_amperaj = models.CharField(max_length=200)
    eficienta = models.CharField(max_length=200)
    certificare = models.CharField(max_length=200)
    poza = models.ImageField(upload_to='sursa', default='dummy_image.jpg')
    reviews = models.ManyToManyField(Review, blank=True)

    class Meta:
        verbose_name_plural = "Surse"

    def __str__(self):
        return f"{self.nume}"


class Carcasa(models.Model):
    nume = models.CharField(max_length=200)
    pret = models.IntegerField()
    cantitate = models.IntegerField()
    separat = models.BooleanField()
    tip_carcasa = models.CharField(max_length=200)
    culoare = models.CharField(max_length=200)
    dimensiuni = models.CharField(max_length=200)
    poza = models.ImageField(upload_to='carcasa', default='dummy_image.jpg')
    reviews = models.ManyToManyField(Review, blank=True)

    class Meta:
        verbose_name_plural = "Carcase"

    def __str__(self):
        return f"{self.nume}"


class Software(models.Model):
    nume = models.CharField(max_length=200)
    pret = models.IntegerField()
    cantitate = models.IntegerField()
    separat = models.BooleanField()
    licentiere = models.CharField(max_length=200)
    licenta_pentru = models.CharField(max_length=200)
    versiune = models.CharField(max_length=200)
    platforma = models.CharField(max_length=200)
    poza = models.ImageField(upload_to='software', default='dummy_image.jpg')
    reviews = models.ManyToManyField(Review, blank=True)

    class Meta:
        verbose_name_plural = "Software"

    def __str__(self):
        return f"{self.nume}"


class Calculator(models.Model):
    nume = models.CharField(max_length=200)
    pret = models.IntegerField()
    cantitate = models.IntegerField()
    procesor = models.ForeignKey(Procesor, on_delete=models.CASCADE)
    placa_de_baza = models.ForeignKey(PlacaDeBaza, on_delete=models.CASCADE)
    placa_video = models.ForeignKey(PlacaVideo, on_delete=models.CASCADE)
    memorie = models.ForeignKey(Memorie, on_delete=models.CASCADE)
    stocare = models.ForeignKey(Stocare, on_delete=models.CASCADE)
    sursa = models.ForeignKey(Sursa, on_delete=models.CASCADE)
    carcasa = models.ForeignKey(Carcasa, on_delete=models.CASCADE)
    software = models.ForeignKey(Software, on_delete=models.CASCADE)
    poza = models.ImageField(upload_to='calculator', default='dummy_image.jpg')
    reviews = models.ManyToManyField(Review, blank=True)

    class Meta:
        verbose_name_plural = "Calculatoare"

    def __str__(self):
        return f"{self.nume}"

shop/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from django import forms

from .models import ExtendUser

class CreateUserForm(UserCreationForm):

	class Meta:
		model = User
		fields = ['username', 'email', 'first_name', 'last_name', 'password1', 'password2']
	
class DetaliiLivrareUser(forms.ModelForm):
	
	class Meta:
		model = ExtendUser
		fields = ['adresa_livrare', 'judet', 'oras', 'cod_postal', 'telefon']
		widgets = {
			'adresa_livrare': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Bulevardul Iuliu Maniu, nr 1-3, Bucuresti', 'required': True}),
			'judet': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Bucuresti', 'required': True}),
			'oras': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Bucuresti', 'required': True}),
			'cod_postal': forms.TextInput(attrs={'class': 'form-control', 'placeholder': '061071', 'required': True}),
			'telefon': forms.TextInput(attrs={'class': 'form-control', 'placeholder': '0712345678', 'required': True})
		}

class DetaliiLivrareNonUser(forms.ModelForm):
	
	class Meta:
		model = ExtendUser
		fields = ['nume', 'adresa_livrare', 'oras', 'judet', 'cod_postal', 'telefon']
		widgets = {
			'nume': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ion Popescu', 'required': True}),
			'adresa_livrare': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Bulevardul Iuliu Maniu, nr 1-3, Bucuresti', 'required': True}),
			'oras': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Bucuresti', 'required': True}),
			'judet': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Bucuresti', 'required': True}),
			'cod_postal': forms.TextInput(attrs={'class': 'form-control', 'placeholder': '061071', 'required': True}),
			'telefon': forms.TextInput(attrs={'class': 'form-control', 'placeholder': '0712345678', 'required': True})
		}

shop/templates/base.html
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <title>PC SHOP</title>

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj"
    crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">

  <style>
    .bd-placeholder-img {
      font-size: 1.125rem;
      text-anchor: middle;
      -webkit-user-select: none;
      -moz-user-select: none;
      user-select: none;
    }

    @media (min-width: 768px) {
      .bd-placeholder-img-lg {
        font-size: 3.5rem;
      }
    }
  </style>


</head>

<body>

  <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'index' %}">PC SHOP</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText"
          aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'index' %}">Acasa</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Periferice
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <li><a class="dropdown-item" href="{% url 'categorie' 'procesoare' %}">Procesoare</a></li>
                <li><a class="dropdown-item" href="{% url 'categorie' 'placi-de-baza' %}">Placi de baza</a></li>
                <li><a class="dropdown-item" href="{% url 'categorie' 'placi-video' %}">Placi video</a></li>
                <li><a class="dropdown-item" href="{% url 'categorie' 'memorii' %}">Memorii</a></li>
                <li><a class="dropdown-item" href="{% url 'categorie' 'stocare' %}">Stocare</a></li>
                <li><a class="dropdown-item" href="{% url 'categorie' 'surse' %}">Surse</a></li>
                <li><a class="dropdown-item" href="{% url 'categorie' 'carcase' %}">Carcase</a></li>
              </ul>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'categorie' 'software' %}">Software</a>
            </li>
          </ul>
          <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'cos' %}">Cos de cumparaturi</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Cont [ {{ user.first_name }} {{ user.last_name }} ]
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <li><a class="dropdown-item" href="{% url 'comenzi' %}">Comenzile mele</a></li>
                  <li><a class="dropdown-item" href="{% url 'user' %}">Schimba datele de livrare</a></li>
                </ul>
            </li>
            <li class="nav-item">
                <a class="nav-link" aria-current="page" href="{% url 'logout' %}">Logout</a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" aria-current="page" href="{% url 'login' %}">Login</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
  </header>

  <main>
    <div class="py-5 bg-light">
      <div class="container">
        {% block content %}{% endblock %}
      </div>
    </div>
  </main>

  <footer class="py-5">
    <div class="container">
      <p class="text-center text-muted">&copy; 2021 PC SHOP</p>
    </div>
  </footer>

</body>

</html>

shop/templates/categorie.html
{% extends "base.html" %}

{% block content %}
<div class="row">
  <h2>{{data.pluralname}}</h2>
</div>
<hr>
{% if data.queries %}
<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
  {% for pq in page_obj %}
  <div class="col">
    <div class="card shadow-sm">
      <!-- Thumbnail -->
      <img src="{{pq.poza.url}}" height="225" alt="produs">
      <!-- Nume si pret -->
      <div class="card-body">
        <a href="/{{data.urlname}}/{{pq.id}}/">
          <h5 class="card-title">{{pq.nume}}</h5>
        </a>
        <p class="card-text" style="color:red; font-size: 160%">{{pq.pret}} RON</p>
        <div class="d-flex justify-content-between align-items-center">
          {% if pq.cantitate > 0 %}
          <a href="{% url 'modifica_cos' 'adauga' data.urlname pq.id %}" type="button" class="btn btn-success">Adauga in
            cos</a>
          {% else %}
          <h5 style="color: red;">Stoc epuizat</h5>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
  {% endfor %}
</div>
<br>
<div class="row" style="margin-bottom: 20px">
  <nav>
    <ul class="pagination">
      {% if page_obj.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}" tabindex="-1" aria-disabled="true">Inapoi</a>
      </li>
      {% else %}
      <li class="page-item disabled">
        <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Inapoi</a>
      </li>
      {% endif %}
      {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
      </li>
      {% else %}
      <li class="page-item disabled">
        <a class="page-link" href="#">Next</a>
      </li>
      {% endif %}
    </ul>
  </nav>
</div>
{% else %}
<div class="row">
  <p>Momentan nu avem niciun produs pe stoc.</p>
</div>
{% endif %}
{% endblock %}

shop/templates/checkout.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
    <h2>Finalizeaza comanda</h2>
</div>
<hr>
<div class="row">
    <div class="col-6">
        <div class="row">
            <h5>Cos de cumparaturi</h5>
        </div>
        <div class="row">
            <div class="table-responsive">
                <table class="table align-middle">
                    <thead>
                        <tr>
                            <th colspan="2" scope="col">Produs</th>
                            <th scope="col">Cantitate</th>
                            <th scope="col">Pret unitar</th>
                            <th scope="col">Pret total</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for p in cos %}
                        <tr>
                            <td><img src="{{p.link_poza}}" height="250" alt="produs"></td>
                            <td>{{p.nume}}</td>
                            <td>{{p.cantitate}}</td>
                            <td>{{p.pret_unitar}} RON</td>
                            <td>{{p.pret_total}} RON</td>
                        </tr>
                        {% endfor %}
                        <tr>
                            <td colspan="3"></td>
                            <td><b>Total cos:</b></td>
                            <td><b>{{total}} RON</b></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="col-6">
        <div class="row">
            <h5>Detalii livrare</h5>
        </div>
        <div class="row">
        {% if user_detalii %}
        <div class="card">
            <ul class="list-group list-group-flush">
              <li class="list-group-item">Adresa livrare: {{user_detalii.adresa_livrare}}</li>
              <li class="list-group-item">Oras: {{user_detalii.oras}}</li>
              <li class="list-group-item">Judet: {{user_detalii.judet}}</li>
              <li class="list-group-item">Cod postal: {{user_detalii.cod_postal}}</li>
              <li class="list-group-item">Telefon: {{user_detalii.telefon}}</li>
            </ul>
        </div>
        <form action="{% url 'checkout' %}" method="POST">
            {% csrf_token %}
            <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                <button type="submit" class="btn btn-primary" style="margin-top: 20px;">Cumpara</button>
            </div>
        </form>
        {% else %}
        <form action="{% url 'checkout' %}" method="POST">
            {% csrf_token %}
            {% for field in form_detalii %}
            <div class="mb-3">
                <label for="">{{field.label}}</label>
                {{field}}
                {{field.errors}}
            </div>
            {% endfor %}
            <button type="submit" class="btn btn-primary">Cumpara</button>
        </form>
        {% endif %}
        </div>
    </div>
</div>
{% endblock %}

shop/templates/comenzilemele.html
{% extends "base.html" %}

{% block content%}
{% if comenzi %}
{% for c in comenzi %}
<div class="row">
    <h2>Comanda nr. {{c.id}}</h2>
    <h3>Status comanda: {{c.status}}</h3>
</div>
<hr>
<div class="row">
    <div class="table-responsive">
        <table class="table align-middle">
            <thead>
                <tr>
                    <th colspan="2" scope="col">Produs</th>
                    <th scope="col">Cantitate</th>
                    <th scope="col">Pret unitar</th>
                    <th scope="col">Pret total</th>
                </tr>
            </thead>
            <tbody>
                {% for p in c.produse.all %}
                <tr>
                    <td><img src="{{p.poza}}" height="250" alt="produs"></td>
                    <td>{{p.nume}}</td>
                    <td>{{p.cantitate}}</td>
                    <td>{{p.pret_unitar}} RON</td>
                    <td>{{p.pret_total}} RON</td>
                </tr>
                {% endfor %}
                <tr>
                    <td colspan="3"></td>
                    <td><b>Total cos:</b></td>
                    <td><b>{{c.pret_total}} RON</b></td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
{% endfor %}
{% else %}
<div class="row">
    Nu ai nicio comanda.
</div>
{% endif %}

{% endblock %}

shop/templates/compara.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
    <a href="{% url 'produs' categorie id %}"><span>&#8592;</span>Inapoi la produs</a>
</div>
<div class="row">
    <h1>Comaparatie produse</h1>
</div>
<div class="row">
    <div class="table-responsive">
        <table class="table align-middle">
          <thead>
            <tr>
              <th scope="col">Caracteristici</th>
              <th scope="col">{{produs1.nume}}</th>
              <th scope="col">{{produs2.nume}}</th>
            </tr>
          </thead>
          <tbody>
            <tr>
                <td>Poza</td>
                <td><img src="{{produs1.poza.url}}" height="250" alt="produs"></td>
                <td><img src="{{produs2.poza.url}}" height="250" alt="produs"></td>
            </tr>
            <tr>
                <td>Pret</td>
                <td>{{produs1.pret}} RON</td>
                <td>{{produs2.pret}} RON</td>
            </tr>
            {% for attr, value in attrs.items %}
            <tr>
              <td>{{attr}}</td>
              <td>{{value.0}}</td>
              <td>{{value.1}}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
</div>
{% endblock %}

shop/templates/register.html
{% extends 'base.html' %}

{% block content %}
<div class="d-flex justify-content-center" style="margin-bottom: 20px;">
    <h3 id="form-title">Creeaza un cont</h3>
</div>
<div class="d-flex justify-content-center">
    <form class="row g-3" method="POST" action="">
        {% csrf_token %}
        <div class="col-12">
          <label for="id_username" class="form-label">Nume utilizator</label>
          {{ formUser.username }}
          {% if formUser.errors.username %}
          <div class="alert alert-danger" role="alert">
            {{formUser.errors.username}}
          </div>
          {% endif %}
        </div>
        <div class="col-md-6">
          <label for="id_password1" class="form-label">Parola</label>
          {{ formUser.password1 }}
          {% if formUser.errors.password1 %}
          <div class="alert alert-danger" role="alert">
            {{formUser.errors.password1}}
          </div>
          {% endif %}
        </div>
        <div class="col-md-6">
          <label for="id_password2" class="form-label">Confirma parola</label>
          {{ formUser.password2 }}
          {% if formUser.errors.password2 %}
          <div class="alert alert-danger" role="alert">
            {{formUser.errors.password2}}
          </div>
          {% endif %}
        </div>
        <div class="col-md-6">
          <label for="id_first_name" class="form-label">Prenume</label>
          {{ formUser.first_name }}
          {% if formUser.errors.first_name %}
          <div class="alert alert-danger" role="alert">
            {{ formUser.errors.first_name }}
          </div>
          {% endif %}
        </div>
        <div class="col-md-6">
          <label for="id_last_name" class="form-label">Nume</label>
          {{ formUser.last_name }}
          {% if formUser.errors.last_name %}
          <div class="alert alert-danger" role="alert">
            {{ formUser.errors.last_name }}
          </div>
          {% endif %}
        </div>
        <div class="col-12">
          <label for="id_email" class="form-label">Adresa de email</label>
          {{ formUser.email }}
          {% if formUser.errors.email %}
          <div class="alert alert-danger" role="alert">
            {{ formUser.errors.email }}
          </div>
          {% endif %}
        </div>
        <div class="col-12">
          <label for="id_adresa_livrare" class="form-label">Adresa de livrare</label>
            {{ formDetalii.adresa_livrare }}
        </div>
        <div class="col-6">
          <label for="id_oras" class="form-label">Oras</label>
            {{ formDetalii.oras }}
        </div>
        <div class="col-6">
          <label for="id_judet" class="form-label">Judet</label>
            {{ formDetalii.judet }}
        </div>
        <div class="col-12">
          <label for="id_cod_postal" class="form-label">Cod postal</label>
            {{ formDetalii.cod_postal }}
        </div>
        <div class="col-12">
          <label for="id_telefon" class="form-label">Numar telefon</label>
            {{ formDetalii.telefon }}
        </div>
        <button type="submit" class="btn btn-primary">Inregistreaza-te</button>
    </form>
</div>    
<script>
  var form_fields = document.getElementsByTagName('input')
  for (var field in form_fields){	
    form_fields[field].className += ' form-control'
  }
</script>
{% endblock %}

shop/templates/user.html
{% extends "base.html" %}

{% block content %}
<div class="d-flex justify-content-center" style="margin-bottom: 20px;">
    <h3 id="form-title">Modifica datele de livrare</h3>
</div>
<div class="d-flex justify-content-center" style="margin-bottom: 20px;">
    <div class="alert alert-primary" role="alert">
        Completeaza datele de livrare inainte sa faci o comanda
    </div>
</div>
<div class="d-flex justify-content-center">
    <form method="POST" action="">
        {% csrf_token %}
        <div class="mb-3">
            <label for="id_adresa_livrare" class="form-label">Adresa de livrare</label>
            {{ form.adresa_livrare }}
        </div>
        <div class="mb-3">
            <label for="id_oras" class="form-label">Oras</label>
            {{ form.oras }}
        </div>
        <div class="mb-3">
            <label for="id_judet" class="form-label">Judet</label>
            {{ form.judet }}
        </div>
        <div class="mb-3">
            <label for="id_cod_postal" class="form-label">Cod postal</label>
            {{ form.cod_postal }}
        </div>
        <div class="mb-3">
            <label for="id_telefon" class="form-label">Numar telefon</label>
            {{ form.telefon }}
        </div>
        <button type="submit" class="btn btn-primary">Actualizeaza</button>
    </form>
</div>
{% endblock %}